check validità codice
tp-it/website pull request #1
Opened 2017-06-28 10:03 UTC by SebastianoPistore

- Verifica validità XHTML e aggiunta logo.
- Correzione glossario (chiusura TAG).

2017-06-28 22:34 UTC, emanueleaina requested changes
Grazie! Ci sarebbe da fare un aggiustamento nella correzione dell'errore, fammi sapere se vuoi aggiornare la pull request o preferisci che lo sistemi io direttamente (citandoti come contributore, ovviamente).

Per i logo, grazie ma no, io eviterei davvero. :D

2017-06-28 22:34 UTC, em- commented on buona_traduzione.html
> +  </p>
Dubito che aggiungendo l'elemento <p> dopo il tag </html> il documento sia ancora valido.

Eviterei in ogni caso di mettere i link al validatore, fanno un po' 1999. :D

2017-06-28 22:34 UTC, em- commented on glossario.html
> +       <p class="notes"/>Il componente dell'architettura X11 che avvia le sessioni per gli utenti, vedi</p> <a href="http://en.wikipedia.org/wiki/X_display_manager_(program_type)">X display manager</
Hah, grazie per averlo notato! Il </p> andrebbe però dopo il punto finale, abbracciando anche l'elemento <a>.

2017-06-29 10:31 UTC, SebastianoPistore commented on buona_traduzione.html
> +  </p>
Si vede che non sono un progettista web... :) ma come si fa a mettere i link al validatore senza cambiare il contenuto della pagina? Prima di fare questo errore non ci avevo mai pensato.

Fanno 1999 tipo questo http://www.catb.org/esr ? A me piacciono un sacco i siti così, davvero. Non scherzo, mi ricordano i siti "seri" di quando ero piccolo.

2017-06-29 10:44 UTC, SebastianoPistore commented on glossario.html
> +       <p class="notes"/>Il componente dell'architettura X11 che avvia le sessioni per gli utenti, vedi</p> <a href="http://en.wikipedia.org/wiki/X_display_manager_(program_type)">X display manager</
In effetti si! Metto subito a posto, grazie.

2017-06-29 11:00 UTC, SebastianoPistore commented on buona_traduzione.html
> +  </p>
Ovviamente cambia come ti sembra opportuno :)

2021-01-13 20:12 UTC, closed without merging

2021-01-22 09:00 UTC, em- commented
Scusami tantissimo, ho finalmente caricato https://github.com/tp-it/website/commit/950c5e1e

Mi sono preso la libertà di correggere diversamente l'errore che hai trovato e di non mettere il link al validatore.

Grazie per la pazienza!